### ISSUE TITLE
Set version for Documentation

### ISSUE THREAD

**Issue by xperseguers** [TYPO3/tailor#1]
A good extension is even better if it features a documentation in ReST within `Documentation/`.

It would be cool that `set-version` would update the version there as well (file `Documentation/Settings.cfg`).

More information: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#settings-cfg

### tl;dr

This is an INI-like file structure and you need to update both `version` and `release` within section `[general]`:

```ini
[general]
project     = File List
version     = 2.5
release     = 2.5.0
t3author    = Xavier Perseguers
copyright   = 2008-2020
description = This extension provides a frontend plugin which
      shows a list of files and folders in a specified directory
      on the file system (comparable to Apache directory listing)
      or using more advanced FAL selectors (categories, collection
      of files, ...). This extension may also be used for creating
      image galleries. Default templates are Bootstrap-ready.
```

**Comment by o-ba** [comment]
Hi, I can't find an explanation for the `version` key. Isn't it the version of the documentation and thus should only be updated in case the documentation content itself got updated? 

There is only an example for `includes.txt` which looks like the format of this key is also not fixed to the [major].[minor].[patch] format.

> .. This files lives at 
   https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/blob/master/Documentation/Includes.txt
   Version: 2018-10-16

**Comment by xperseguers** [comment]
Best practices in the context of extension authors show that this is the [major].[minor] version. The documentation team and the server do not expect changes in the documentation in patch release and as such only show various versions of an extension's documentation by [major].[minor].

See https://docs.typo3.org/p/causal/image_autoresize/2.0/en-us/ and the "Release" link in the navigation menu on the right. Corresponding source is https://github.com/xperseguers/t3ext-image_autoresize/blob/master/Documentation/Settings.cfg and you see that the naming for the documentation server is mixing-up Sphinx/ReST-related configuration options Release and Version but the point is there, if you ask the documentation team, the indeed only show doc for [major].[minor].

**Comment by o-ba** [comment]
Alright, thanks for the explanation. I'll look into this.

**Comment by bmack** [comment]
@xperseguers can you provide a regexp to achieve this?

**Comment by xperseguers** [comment]
A regexp for replacing the version number? Well basically this should do the work:

```
/^(version\s*=\s*)(.*)$/
```

replace matched group 2 by the new version and keep group 1 as-is would ensure any custom formatting would be kept.

Do the same for the `release` and that's it...

**Comment by o-ba** [comment]
Hi @xperseguers, could you please have a look at the PR. Thanks in advance.
