### ISSUE TITLE
[BUG] Does not work with TYPO3 9 composer

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/tailor#10]
## Summary / Description

It's not possible to add tailor via composer to a TYPO3 9 installation because of the dependencies of symfony/console.

Seen in use at https://github.com/b13/menus/blob/master/composer.json#L16

## Version

All

## Steps to reproduce

Have a TYPO3 9 installation based on composer and execute:

`composer req typo3/tailor --dev`

## Expected behaviour

It can be installed

## Actual behavior

`typo3/tailor 1.1.0 requires symfony/console ^5.1 -> found symfony/console[v5.1.0, ..., v5.2.0] but the package is fixed to v4.4.17 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

**Comment by o-ba** [comment]
Hi @simonschaufi, please have look at the PR: #11 

To test it in your project you can use `composer req --dev typo3/tailor:dev-lower-dependencies`
