### ISSUE TITLE
[BUG] Wrong exit code after successful extension publish

### ISSUE THREAD

**Issue by spoonerWeb** [TYPO3/tailor#2]
I wrote a GitLab CI configuration to upload my extension to TER via tailor.
It suceeds with upload but my job was marked as failed, see: https://git.spooner.io/spooner-web/tcabuilder/-/jobs/7249.

It should exit with the correct exit code "0".

**Comment by o-ba** [comment]
Thanks for reporting this issue. This is fixed with https://github.com/TYPO3/tailor/commit/774e0050421d0a013e85ca1001167af18da10da3.
