### ISSUE TITLE
[BUG] Transfer-Encoding missing

### ISSUE THREAD

**Issue by gilbertsoft** [TYPO3/tailor#50]
The Transfer-Encoding header is currently missing for POST request which leads to a negative score on the server side. It should be submitted properly where needed to avoid further issues.

**Comment by o-ba** [comment]
Hi, thanks for creating an issue. How can this be reproduced / tested? As for my understanding, access to the server logs would be required, right?

**Comment by o-ba** [comment]
Hi @gilbertsoft,  I'm closing this for the time being, since no additional information had been provided regarding how this can be tested or reproduced. Please feel free to add more information anytime.
