### ISSUE TITLE
[BUG] extension code was published in wrong extension

### ISSUE THREAD

**Issue by clickstorm** [TYPO3/tailor#56]
## Summary / Description

cs_seo version 6.6.0 was now released as go_maps_ext

In detail:
https://extensions.typo3.org/extension/go_maps_ext has now a release 6.6.0 of cs_seo https://extensions.typo3.org/extension/cs_seo

## Version

Version in which the bug occurs.

## Steps to reproduce

I have to two extenions in my local project. I changed the .env variables from one extension to another. Than I wanted to publish the extension via tailor ter:publish cs_seo. It happend that my extension was published as the other extension, which was set in the .env before. 

## Expected behaviour

How can I prevent this in the future?

**Comment by mhirdes** [comment]
The version of tailor was 1.4.1

**Comment by o-ba** [comment]
Hi, I fear I don't fully understand what happened here in detail.

> I changed the .env variables from one extension to another

So which keys have been changed? Which key was present wenn publishing the `go_maps_ext`?

> Than I wanted to publish the extension via tailor ter:publish cs_seo. 

Providing an extension key as cli argument always takes precedence over an extension key, defined as env var. This means if you provided `cs_seo` as extension key, the new version is published for this extension, no matter the env var.

**Comment by o-ba** [comment]
I'm closing this for the time being, since no additional information had been provided. I'm also not able to see how this issue is related to the functionality of tailor. Please feel free to add more information anytime.
