### ISSUE TITLE
[BUG] Documentation has not been rendered since 2021

### ISSUE THREAD

**Issue by linawolf** [TYPO3/tailor#77]
There is rendered Documentation of this Repository at https://docs.typo3.org/other/typo3/tailor/main/en-us/ which has not been rerenderered since 2021. Should we delete it from intercept or would you like to create a github action triggering re-rendering?

**Comment by o-ba** [comment]
Thanks for pointing this out. I added corresponding webhook. The documentation will now be automatically updated / rendered on push.
